### ISSUE TITLE
No system presence

### ISSUE THREAD

**Issue by DynFaust** [Roger92/metric-ruler-labels#11]
Hi,

Sorry for my English, i speak ordinary French.

I love your module ! This is what i was looking for a long time ! Thanks !
But I can't get it to work... It's like I didn't install it. I tried with a blank project but I have the same problem.

I show you my configuration:

![screenDynFaust](https://user-images.githubusercontent.com/108682311/177179564-ef25f439-2726-4079-a450-1a1fe3ab2fda.jpg)

Can you help me ?

**Comment by Roger92** [comment]
I can try.

Can you show me how it looks when you use the ruler.

And can you show me the Settings of the module (Click Configure Settings -> Go to modules -> Mine should be somewhere at the top) :)

**Comment by DynFaust** [comment]
Thanks !

here, first part of the parameters, and on the left the use of the ruler : 

![screenDynFaust2](https://user-images.githubusercontent.com/108682311/177206630-9e3a362d-12e0-43a6-89f9-55a51092fe2e.jpg)

Second part of the parameters :

![screenDynFaust3](https://user-images.githubusercontent.com/108682311/177206792-dd20a0cf-44de-4cfa-bb75-69471a089b6a.jpg)


**(When I saw it didn't work, I changed the original label to see if it showed up, that's why I put fXt)**

.

**Comment by Roger92** [comment]
try to put ft without the dot in the "Original Unit label Small Unit" box :) There it should always be the label that is normally displayed on your ruler, which is ft

If that still doesn't work please open the Developer console (F12 on Chrome), Select the console tab and screenshot any error that appears, when you use the ruler :)

**Comment by DynFaust** [comment]
I have a error :

![screenDynFaust4](https://user-images.githubusercontent.com/108682311/177210939-1fb3726a-8653-4d32-bca2-fe79297ecf3b.jpg)

**Comment by Roger92** [comment]
hmmm weird, that it complains about libWrapper.... can you disable all modules except mine and libwrapper? ... so please diasable libruler and restart foundry :)

**Comment by DynFaust** [comment]
I have more errors :

![screenDynFaust5](https://user-images.githubusercontent.com/108682311/177213398-aace5a35-85fe-46f9-9cc3-fc6f482a59e8.jpg)

**Comment by Roger92** [comment]
seems like libwrapper problem... do you get the same with just libwrapper activated?

**Comment by DynFaust** [comment]
Same problem as for the test before. Looks like the problem is libwrapper... or my config ???

![screenDynFaust6](https://user-images.githubusercontent.com/108682311/177386743-124a2232-120d-41b1-934a-c48c86119c2d.jpg)

**Comment by Roger92** [comment]
hmm yah its weird... the "libwrapper not defined" looks like that that libWrapper module is not loaded. 

Maybe uninstall and reinstall libwrapper again :)

**Comment by DynFaust** [comment]
There is progress! Now everything works except the custom units. I can't access anything other than meter, even if I change the custom unit in the config.

**Comment by Roger92** [comment]
We are getting there :)

So whats the unit of the scene / on your current ruler?
And whats on your config... can you screenshot both? :)

**Comment by Roger92** [comment]
You have to put the labels that you want to convert into the "Original unit label" Box... In your case it would be m instead of "ft., feet"

**Comment by Roger92** [comment]
![image](https://user-images.githubusercontent.com/11605051/177393511-28884277-aaae-49e0-b731-9993a91ceb35.png)

**Comment by DynFaust** [comment]
Yes it's work perfectly ! Thanks very very much ! Thank you for taking the time to help me, my players will be delighted and thank you.

**Comment by Roger92** [comment]
No Problem, glad to see that this module helps some people :) Have a nice evening 👍
