### ISSUE TITLE
PF2e metric don't work 

### ISSUE THREAD

**Issue by Sasmira** [Roger92/metric-ruler-labels#13]
Hello Hello,

The module don't work with PF2e 
<img src="https://puu.sh/JnKde/ef123ac9fc.png">

A fix for drag ruler has been create for v10 here 
https://github.com/Traumi/foundryvtt-drag-ruler

thx for your help

**Comment by Roger92** [comment]
Heyho @Sasmira ,

let me try to understand... so you provided a fix for drag-ruler to work with v10 right? 
And then the problem is that my module is not working with the v10-fixed version for dragruler, am i correct?

I was not able to test the dragRuler integration on V10 because there was and still is no official v10 version for dragruler.

But did i understand the problem correctly? I wont have time this weekend but i can look into it next week. So that it works with traumi's temporary fix :)

**Comment by Sasmira** [comment]
> Heyho @Sasmira ,
> 
> let me try to understand... so you provided a fix for drag-ruler to work with v10 right? And then the problem is that my module is not working with the v10-fixed version for dragruler, am i correct?
> 
> I was not able to test the dragRuler integration on V10 because there was and still is no official v10 version for dragruler.
> 
> But did i understand the problem correctly? I wont have time this weekend but i can look into it next week. So that it works with traumi's temporary fix :)

Hello Hello !

Yes ! you have totaly understand the problem ! Metric ruler label don't work with Drag ruler Traumi version for v10.

thx for your help !
S.

**Comment by Roger92** [comment]
Ah alright, perfect... i will try to provide a fix next week so that it works with the temporary solution from Traumi :)

**Comment by Roger92** [comment]
Heyho @Sasmira ... i looked into it and i am having trouble to access the ruler labels on Traumis patch. Traumi is not using the foundry Ruler Class to update the ruler, so i currently cant intercept the update on the ruler to add my labels... 

I will try some stuff. Manuel planed to update DragRuler this or next week (this week is over so i guess the update is coming next week) ... maybe it will be easier for me to make changes according to his version.

I will post an update here once i found a way to get it working with Traumis patch or if i found a way for the original :)

**Comment by Roger92** [comment]
Alright, the new version is there... hopefully i have time today to look at it... otherwise it would be the beginning of next week :)

**Comment by Sasmira** [comment]
nice ! thx for your work !

**Comment by Roger92** [comment]
@Sasmira  aaaaalright... had some time today and i think i got it :D Will do some testing tomorrow and then there might be a new version tomorrow :) Sorry for the long wait.

**Comment by Sasmira** [comment]
> aaaaalright... had some time today and i think i got it :D Will do some testing tomorrow and then there might be a new version tomorrow :) Sorry for the long wait.

hey nice ! sound good !

**Comment by Roger92** [comment]
Alright... should work again :)  Version 2.1.2 is available

**Comment by Roger92** [comment]
Should be wirking since 2.1.2 :) If not reopen it.
