### ISSUE TITLE
[Feature Request] Add support for several outputs per input value

### ISSUE THREAD

**Issue by SirMotte** [Roger92/metric-ruler-labels#15]
If it is not too much trouble I'd be glad to have the option to add additional output entries to show per input. If this would require a lot of coding, it's not worth the effort, as this is probably a niche use case.

Use case example - Travel Time:
Travel Distance:
Input: x Miles 
- Output 1: x km
- Output 2: x days slow
- Output 3: x days normal
- Output 4: x days fast

**Comment by Roger92** [comment]
That's actually a nice idea... I will look into that l.

**Comment by Roger92** [comment]
Hmm yah maybe something like 

x Miles
y km
A | B | C Days

That would not take up too much space 🤔 So it would be (slow | normal | fast ) 

And i guess it would be the easiest to stick to the perDay Travel distances (so calculate everything on the X km per day value)... otherwise it would get kinda crowded with information. At least in DnD its different travel distances per day / hour / minute if i remember correctly. Dont know how its like in other systems like pathfinder etc.

**Comment by SirMotte** [comment]
> Hmm yah maybe something like
> 
> x Miles y km A | B | C Days
> 
> That would not take up too much space 🤔 So it would be (slow | normal | fast )
> 
> And i guess it would be the easiest to stick to the perDay Travel distances (so calculate everything on the X km per day value)... otherwise it would get kinda crowded with information. At least in DnD its different travel distances per day / hour / minute if i remember correctly. Dont know how its like in other systems like pathfinder etc.

Yes, DnD does use different values depending on creature speed and travel pace.

I think you're on the right path there, as long as I can input a custom value for each output, as I use a custom travel pace value loosely based on roman legions travel speed. So if I have the option to put in values that resemble normal or forced march for the per day output fields I'm a happy GM.

Having the output set up like you suggest is a sensible decision, good thinking.

An insanely useful addition support for the Enhanced Terrain + Terrain Ruler Modules but I'm daydreaming now. I have no clue how difficult this would be, in addition, those modules seem to break on regular basis, so a dependency would be risky.

**Comment by Roger92** [comment]
Doesnt have drag-ruler built-in support for some terrain module? 🤔  

Currently on the finishing tests for the dragruler update. Will leave screenshot here when i have something to show for the travel stuff :)

**Comment by SirMotte** [comment]
> Doesnt have drag-ruler built-in support for some terrain module? 🤔
> 
> Currently on the finishing tests for the dragruler update. Will leave screenshot here when i have something to show for the travel stuff :)

Awesome.
As far as I know, (Could be wrong, has been a while since I last used enhanced terrain), I needed an additional modules called Terrain Ruler, that tied into the dragruler and terrain ruler api, for everything to work properly.

I could be wrong about this. Will investigate this in the coming days.

**Comment by SirMotte** [comment]
I just gave the enhanced terrain module another go, but it still seems to be broken with terrain ruler. But yes, you're right, your module will work without dedicated support for anything terrain layer, so this is a big plus.

**Comment by Roger92** [comment]
And maybe try it without my module first... not that my module is the cause why dragRuler doesnt work with terrain ruler :D

**Comment by SirMotte** [comment]
Nope, I already made sure of this. I just looked through the issue thread of enhanced terrain and there are fixes waiting for release, so that's that :)

**Comment by Roger92** [comment]
![image](https://user-images.githubusercontent.com/11605051/197414565-a3f5d69b-85e2-4749-bb57-6604de87b180.png)

![image](https://user-images.githubusercontent.com/11605051/197414652-6713de33-a600-45ea-a5dd-68aa1b3f4d7a.png)


What do you think?

I rounded the days to quarters... i guess thats precise enough.

**Comment by SirMotte** [comment]
That is absolutely perfect :)

**Comment by Roger92** [comment]
yep

**Comment by SirMotte** [comment]
Awesome. this is perfect!

**Comment by Roger92** [comment]
Thx alot. Always nice to hear that the module helps people ... I guess i will do a release in the next days :) I wanna try if i can fix the behaviour on gridless scenes, so i can put it together in a release :)

**Comment by SirMotte** [comment]
Take your time, no need to rush. Looking forward to it.

**Comment by Roger92** [comment]
FYI: Aaaaaalright... i think i found a way to fix the behaviour with dragruler on gridless scenes... expect an update in the next days together with the travel times ;)

**Comment by SirMotte** [comment]
> FYI: Aaaaaalright... i think i found a way to fix the behaviour with dragruler on gridless scenes... expect an update in the next days together with the travel times ;)

Hussah! Congratulation! Looking forward to it <3

**Comment by SirMotte** [comment]
Testing V3 now

**Comment by Roger92** [comment]
Should now be available via froundry too :)

**Comment by SirMotte** [comment]
Working perfectly. Just what I was hoping for, and even easier to handle than what I came up with. Thank you for your hard work!

**Comment by Roger92** [comment]
Nice to hear :) Let me know if they liked it or not :)

**Comment by SirMotte** [comment]
> Nice to hear :) Let me know if they liked it or not :)

Will do...why wouldn't they^^. They should be damn grateful ;D
