### ISSUE TITLE
Travel Time does not show for total distance moved

### ISSUE THREAD

**Issue by PepijnMC** [Roger92/metric-ruler-labels#20]
From core, holding control will let you place waypoints when measuring but the travel time is only shown for the last segment. It would be very helpful if the total travel time can also be shown.

**Comment by Roger92** [comment]
Oh yah, it should be on every waypoint... Will check that.

**Comment by SirMotte** [comment]
Wanted to report this as well. I did some more in depth testing yesterday and was confused at first, but I though another module might be at fault. Good to know that it's not an incompatibility.

**Comment by Roger92** [comment]
Found the issue :) Fix will come tomorrow :)

**Comment by Roger92** [comment]
And i think that there is also some kind of additional bug... The Ruler with waypoints works normally like that. Each waypoint shows the distance from the previous waypoint to the current. Except the last one shows also the complete distance in the [ ] brackets.

The travel times on the other hand dont have these complete distance behaviour... but i guess the last waypoint should also have this complete travel time in brackets... what do you think @SirMotte @PepijnMC

**Comment by SirMotte** [comment]
> [...] but i guess the last waypoint should also have this complete travel time in brackets... [...]

That's what I would expect, yes.

**Comment by Roger92** [comment]
Then we think the same... 👍 will add that to the fix.

**Comment by SirMotte** [comment]
On second thought, If we have a massive **0.75 | 0.75 | 0.75 [ 43 | 30 | 20 ]** Textblock, I'd opt for only the total days shown instead. Another line on the other hand should work, but this starts to feel crowded already.

**Comment by Roger92** [comment]
Fixed in 3.1.0 ... Have fun :)

**Comment by Roger92** [comment]
> On second thought, If we have a massive **0.75 | 0.75 | 0.75 [ 43 | 30 | 20 ]** Textblock, I'd opt for only the total days shown instead. Another line on the other hand should work, but this starts to feel crowded already.

yaaaaah just read this :D it gets crowded for sure :D

**Comment by Roger92** [comment]
Aaaaand i put in a toggle on 3.1.1 ;)

**Comment by SirMotte** [comment]
I can confirm, that everything is working perfectly and as advertised.

**Comment by Roger92** [comment]
Always ;) I dont do false advertising :D  Have a great weekend you two.
