### ISSUE TITLE
Allow the time unit for travel times to be configurable.

### ISSUE THREAD

**Issue by PepijnMC** [Roger92/metric-ruler-labels#21]
Currently the travel time uses days but it would be great if this can be configured to whatever unit the user wants, for example hours. The configured travel times can simply be for the configured time unit.

**Comment by Roger92** [comment]
yah good point :)

**Comment by Roger92** [comment]
See 3.1.0 :)

**Comment by SirMotte** [comment]
I consider this request to be fulfilled. Thank you very much!
