### ISSUE TITLE
[API] - return waypoints and distances

### ISSUE THREAD

**Issue by rinnocenti** [Roger92/metric-ruler-labels#22]
I have a travel pace module (https://github.com/rinnocenti/travel-pace), and I wanted to improve it with your module.
Can you create an API in your module returning an array/hash with each measured waypoint?

because I want to make the thing more automatic, today it's just a calculator.

**Comment by Roger92** [comment]
So you want an array with values from the currently active ruler?

So this:
![image](https://user-images.githubusercontent.com/11605051/201443249-baa41ac8-6280-4906-97fa-7b9f7c4bb208.png)

Would return something like:

`[
  {foundry: "10 miles",customConversion:"16.09 km",travelTimes: "0.50 | 0.50 | 0.25 Days"},

  {foundry: "10 miles [20 miles]",customConversion:"16.09 km [32.19 km]",travelTimes: "0.50 | 0.50 | 0.25 Days"}  
]`

Or what do you mean?

**Comment by Roger92** [comment]
hmmm so for the case the people are using ft/miles and then the metric conversion 🤔

**Comment by Roger92** [comment]
try the following on 3.1.0 ... i put in a quick api:

![image](https://user-images.githubusercontent.com/11605051/201475129-f91a3055-0077-4866-8887-bbbcf67e5ff1.png)

**Comment by Roger92** [comment]
The current requirement is that the user is using one of the following measurements in the scene:

- ft
- feet
- mi
- miles
- mile
- m
- meter
- meters
- km
- kilometer
- kilometers

**Comment by rinnocenti** [comment]
I'm taking the tests this weekend.
But I believe it will work.
I'll just need to think of a way to gather the information from difficult terrain.
but this information will help a lot, thank you
