### ISSUE TITLE
[Feature Request] Add module settings for set on client side Metric and Imperial explicitily

### ISSUE THREAD

**Issue by p4535992** [Roger92/metric-ruler-labels#26]
I have a group where half use the interface with metric language (e.g. Germany) and the other half use imperial distance (e.g. USA), for all of them I would like to show both the option in meters and feet, with the current settings modules this is not possible.

Can you add client side settings modules to explicitly enable metric or imperial distance for the second label ?
Something like:
 "Add metric distance as secondary measurement"
"Add imperial distance as secondary measurement"

If both are selected just check what the first measurement use and choice the other ?

**Comment by Roger92** [comment]
Hmm i am not sure if i understand you completely.

What measurement do your scenes have? If they are feet (which would be imperial) and the metric conversions are activated, then everyone should see both imperial and metric (if you dont hide the foundry labels)

**Comment by p4535992** [comment]
Sorry completely forgot about this. It was a stupid question. The module already do that, i just need to sync the settigns between players.
