### ISSUE TITLE
Drag Ruler with hiding Foundry Measurments does not work

### ISSUE THREAD

**Issue by Radulf321** [Roger92/metric-ruler-labels#27]
Hi,
I'm really glad to have found your module :) Thanks a lot for that. My German group will really enjoy to finally play in metric system!
However, I found a small bug. I also use Drag Ruler and since I don't care about feet, I activated the option to hide the measurements of Foundry. Now, when I drag a character and the Drag Ruler is activated, the correct measurement (in meters, without feet) is shown for a short duration and then disappears. Once I disable the option to hide the measurements, everything works fine. I validated this bug and deactivated all other modules, except for Drag Ruler, your module, and their requirements. We play Pathfinder 2e, in case that is relevant. Foundry and all modules should be up to date:
- Additional Metric Ruler Labels: 3.1.1
- Drag Ruler: 1.13.2
- libWrapper: 1.12.11.0
- socketlib: 1.0.12
- Foundry: 10.290
- Pathfinder 2e: 4.4.2

If I can provide you with any more information, feel free to ask. Thank you for your effort!

**Comment by Roger92** [comment]
Thx for the post... i will take a look somewhere during the next days :)

**Comment by Roger92** [comment]
Oh yah you are right... i can reproduce that on my end :) I guess there will be a fix in the coming week :) Until then, just dont hide the foundry  labels ;) ... And nice to hear that my module helps you

**Comment by Roger92** [comment]
Found the culprit :) Will push a fix tomorrow.

**Comment by Radulf321** [comment]
Wow, that's fast :) Thanks a lot! I did not expect to have the fix for our session tomorrow :)

**Comment by Roger92** [comment]
Should be fine now :) ... The little flickering of the labels when moving is a known thing... But currently i cant get rid of them, given the way i overwrite the dragruler labels.

**Comment by Roger92** [comment]
Does it work now? :) Or do you see still problems @Radulf321

**Comment by Radulf321** [comment]
I only got to test it now. But it works great! Thank you for your fast handling!
