### ISSUE TITLE
Installation Error: did not provide module manifest data.

### ISSUE THREAD

**Issue by mrjaksauce** [Roger92/metric-ruler-labels#29]
Error: Unable to load valid module manifest data from "https://github.com/Roger92/metric-ruler-labels/releases/tag/v0.9.1/download/module.json"
The requested manifest at "https://github.com/Roger92/metric-ruler-labels/releases/tag/v0.9.1/download/module.json" did not provide module manifest data.

**Comment by Roger92** [comment]
Heyho, sorry for the wait... i will check it tomorrow :)

**Comment by Roger92** [comment]
I really dont know why this suddenly happened :D I think i fixed the manifest links now ... can you try again @mrjaksauce @UchihaPhantom @Luisphigor @DragonHale

**Comment by Roger92** [comment]
3.1.4 is out... at least for me it solves the problem after:

1. Uninstall
2. Restart Foundry
3. Install again 

:) Let me know if that fixes it.

**Comment by Roger92** [comment]
Fixed
