### ISSUE TITLE
Elevation ruler integration

### ISSUE THREAD

**Issue by EgresMC** [Roger92/metric-ruler-labels#30]
The module doesn't work with the [Elevation ruler module](https://github.com/caewok/fvtt-elevation-ruler) enabled.

Maybe it's because the Elevation ruler adds a second row of distance on its own (the second row shows the elevation of the token).

In fact, where there's no elevation involved (like in the AoO templates) the Metric ruler labels module works flawlessly despite the Elevation ruler.

**Comment by Roger92** [comment]
Heyho.... Never used elevation ruler personally. Will take a look maybe on the weekend if I have some time :)

**Comment by EgresMC** [comment]
Thank you for your time.

**Comment by Roger92** [comment]
Hmmm seems to work for me.... can you give me a screenshot?

![image](https://user-images.githubusercontent.com/11605051/218189016-4c923e87-ef3b-4c30-b8ab-91ae8e2ece6a.png)

**Comment by EgresMC** [comment]
Hi there.

I'm attaching three images: one with an AoE template (that shows the metric), one with a ruler measurement (that shows the metric as well), and the last one with a token mevement (which doesn't show it in metrics).

![AoE with metric](https://user-images.githubusercontent.com/124737818/218267167-19f33ee6-b808-466a-a0a8-c26bed456662.jpg)
![Ruler with metric](https://user-images.githubusercontent.com/124737818/218267172-21494fdd-126a-4b5b-bf9d-6336499249e4.jpg)
![Movement with no metric](https://user-images.githubusercontent.com/124737818/218267176-e42b892b-413c-4d14-aa43-d1b558ba128a.jpg)

Thanks again for your time and effort.

**Comment by Roger92** [comment]
Ahhh ok... Then it's the dragruler ... You have dragruler installed, right?

**Comment by EgresMC** [comment]
Sorry for the late reply.

Yes, I have Dragruler installed.

**Comment by Roger92** [comment]
Should be fixed on 3.1.5 :) 

I will add a conversion for the elevation itself to my future feature list :)  But the normal distance conversions should be displayed again.

**Comment by EgresMC** [comment]
It works perfectly!

Thank you again!
