### ISSUE TITLE
[Issue] Update Error -> undefined

### ISSUE THREAD

**Issue by SirMotte** [Roger92/metric-ruler-labels#31]
![grafik](https://user-images.githubusercontent.com/82598692/217906718-5273fcce-27a7-41e2-bcc9-5550bceb9ee4.png)
It seems there is something going wrong with the latest version. Any time I check for updates the module is updated and the history shows this.

**Comment by Roger92** [comment]
Hmmm ... Ich gucke mal ob ich das bei mir reproduzieren kann ... Ich hatte plötzlich Probleme mit den Links zu den manifest Dateien. Musste die diese Woche aktualisieren. Vllt ist er daher durcheinander gekommen.

Haste es schonmal neu installiert?

**Comment by SirMotte** [comment]
> Hmmm ... Ich gucke mal ob ich das bei mir reproduzieren kann ... Ich hatte plötzlich Probleme mit den Links zu den manifest Dateien. Musste die diese Woche aktualisieren. Vllt ist er daher durcheinander gekommen.
> 
> Haste es schonmal neu installiert?

Probier ich gleich mal aus. Moment.

**Comment by nschoenwald** [comment]
Habe das gleiche Problem: 
<img width="604" alt="image" src="https://user-images.githubusercontent.com/72390280/218128816-fe590533-bc20-4ea2-81cb-342379b500c9.png">

**Comment by Roger92** [comment]
Ah jez sehe ich es auch... ich schaue mal :D

**Comment by Roger92** [comment]
OK 3.1.4 out .... @nschoenwald @SirMotte  Bitte einmal uninstall und install :)

**Comment by nschoenwald** [comment]
Ging auch ohne Neu-Install, habe nur geupdated und jetzt sieht alles gut aus.

**Comment by SirMotte** [comment]
Neu Installation war bei mir notwendig, nun läufts, danke!
