### ISSUE TITLE
Module Incompatibility with Foundry VTT Version 12

### ISSUE THREAD

**Issue by Niclasp1501** [Roger92/metric-ruler-labels#41]
I have encountered an issue with the module, which does not function properly with the latest Foundry update. The module was working perfectly in previous versions but appears to be incompatible with the latest version.

**Comment by Roger92** [comment]
Heyho, thanks for the info... I will maybe have a look this weekend. :)

**Comment by Roger92** [comment]
Alright, will now look into it... would be great if you can verify that it works on your end once i pushed a new version @Niclasp1501  :)

**Comment by Roger92** [comment]
OK... Version 3.2.0 is out and it should work again on V12. Keep in mind that the DragRuler support doesnt currently work, because dragRuler doesnt support V12 yet. When Manuel updates his module i will check if i need to do any adjustments to support dragRuler again :) 

Does it work on your end @Niclasp1501 ?

**Comment by Niclasp1501** [comment]
Hi @Roger92 , I'm not available at the moment, but I will test it later or by tomorrow at the latest and provide feedback. Thanks a lot for your work!

**Comment by Roger92** [comment]
Sounds good, no hurry :)

**Comment by haho76** [comment]
I am not sure if DragRuler really will be updated. Is it possible you check if your module can work with ElevationRuler - that´s liekly the goto replacement for DragRuler everyone is going to use. It´s done be Aedif, who has their own channel on Posney´s (MidiQOL) discord.....

**Comment by Roger92** [comment]
Just read today, that dragRuler will be updated.

But yeah already thought about trying elevation ruler. And if i interpret the patreon vote for V13 correctly, then something like dragRuler will become part of core foundry

**Comment by Roger92** [comment]
just tried... it should work with elevation ruler ;) Only the actual elevation is not parsed.

**Comment by Niclasp1501** [comment]
I have tested it, and the normal function is working again. When I opened the issue here, I was too hasty. The faulty behavior I mentioned was actually due to 'DragRuler'. Nonetheless, thank you very much for your work and for adjusting it once DragRuler gets an update.

**Comment by Roger92** [comment]
No problem :) ... But you were not wrong... My module also had a little issue... It was not loading because it didn't update my manifest to tell foundry that it's compatible .  The max version was 11 ;)

**Comment by Roger92** [comment]
Seems to be fixed :)
