### ISSUE TITLE
Feature request : Integration with PF2e Token Drag Ruler

### ISSUE THREAD

**Issue by theksi** [Roger92/metric-ruler-labels#47]
Hello,
At this stage, Drag ruler as such has not been updated for V12 , though a module named "[PF2e Token Drag Ruler](https://github.com/7H3LaughingMan/pf2e-ruler)" enables alike features for Pathfinder 2. 

I haven't been able to have metric-ruler-labels working with this module and I hereby suggest, if feasable that you could work on an integration.

**Comment by Roger92** [comment]
Thx for the suggestion... i will have a look :)

**Comment by Roger92** [comment]
@theksi Alright... should work now with the current version 3.2.2 ... But i also noticed that the module you mentioned is not maintained anymore :) ... But the build in dragruler in the PF2e system should work also :)
