### ISSUE TITLE
Warning in Foundry 12

### ISSUE THREAD

**Issue by MSAbaddon** [Roger92/metric-ruler-labels#48]
Foundry 12 currently throws a warning for this module:

![image](https://github.com/user-attachments/assets/312431f0-bac0-48dd-909e-18a98fb2bc08)

**Comment by Roger92** [comment]
Oh thx for the report... did you notice any weird behaviour? or is it just the warning in the console? @MSAbaddon

**Comment by MSAbaddon** [comment]
As far as I can tell the module works fine. The warning is directly on the starting page however, so I guess it would be nice to get this removed.

![image](https://github.com/user-attachments/assets/aed8d135-eb4d-4210-8620-5dcf16250e6f)

**Comment by Roger92** [comment]
Should be gone in the next update (today or tomorrow) :)

**Comment by Roger92** [comment]
Should be fixed now in the current version 3.2.2 :)

**Comment by MSAbaddon** [comment]
Version 3.2.2 creates the following warning message:
![image](https://github.com/user-attachments/assets/43ed3ac4-53b1-4d1a-b8fe-69ffc2bbb3b0)

**Comment by Roger92** [comment]
fix one, get one new xD .... i might have a look in the next days... thx... Is it only showing up in the console or also in Foundry itself?

**Comment by MSAbaddon** [comment]
Both console and Foundry

**Comment by Roger92** [comment]
Alrighty, the warning shoudl be gone now with version 3.3.1 :) @MSAbaddon

**Comment by MSAbaddon** [comment]
It's gone - big thanks :-)
