### ISSUE TITLE
Not Working on V9

### ISSUE THREAD

**Issue by Ychabod** [Roger92/metric-ruler-labels#5]
From all the non-imperial unit users, thanks for this module ! 

Im on V9, the module seems not working on template ruler, but works with the natural ruler :)

**Comment by Roger92** [comment]
Thank you very much for the feedback :) Nice to hear that it helps someone. Didn't had time yet to check V9... Maybe this weekend.

**Comment by Roger92** [comment]
Heyho @Ychabod  :) The fix is out and it should now work on V9.

I wish you a great weekend. And thx for the bugreport.
