### ISSUE TITLE
Support PF2e integrated ruler with Difficult Terrain

### ISSUE THREAD

**Issue by NBSamael** [Roger92/metric-ruler-labels#52]
Hi,

With new version of Pathfinder 2e system, there is no need for a drag ruler anymore.
The additional metric ruler label works with this feature in a basic way :
![image](https://github.com/user-attachments/assets/609d711d-b5b2-4389-b98a-3146fb776d17)

but if you use areas with difficult terrain, the conversion display disappears :
![image](https://github.com/user-attachments/assets/8766a1b3-48ad-41b7-8c67-b769f21e74ba)

Can you please check if you can fix this in your mod?
By tha way, all non-americans foundry users thank you for this mod :)

**Comment by Roger92** [comment]
I will have a look during this week :) ...  And always great to hear that is helps people.

I am not experienced with the pathfinder system in foundry. Do you have mods for the difficult terrain? and if yes which one? 
If not how do i add a difficult terrain area in there? ;) @NBSamael

**Comment by NBSamael** [comment]
It's build-in with the system.
You create a region et you add an environment feature : 
![image](https://github.com/user-attachments/assets/7d4613f2-a9f8-4b85-95b1-46f599d96576)

**Comment by Roger92** [comment]
ah nice, thanks... i will have a look.

**Comment by Roger92** [comment]
Any idea why the difficult terrain is not applying on my side?
![image](https://github.com/user-attachments/assets/9fd53246-e154-4979-ba3d-52374c57b4bb)
![image](https://github.com/user-attachments/assets/6378deff-c46f-43ee-bdf3-49e18d972af5)

**Comment by NBSamael** [comment]
Oh I'm sorry but I thought it was a feature embedded with the PF2e system.

In fact you can find this feature with two modules :
- The one I was using when I made the captures was "Easy Region" with the "Show cost on ruler" option enabled
- Since that a new module has been released: "PF2e Drag Measurement Action Icon" which has a nicer display with the number of actions that the move costs

![image](https://github.com/user-attachments/assets/98c37f06-74b9-44e2-bf28-dface131f90d)
![image](https://github.com/user-attachments/assets/6f8b6c37-9237-492e-bde7-256f6399a988)

But I don't know if you work from the displays of other modules

**Comment by Roger92** [comment]
I will have a look... i have some spare time today... so maybe i can add it :)

**Comment by Roger92** [comment]
I found a nicer way to do the conversions of the labels :) Its now more dynamic and should work better with different types of labels, right out of the box :) 

There might be an update tomorrow ;)

**Comment by Roger92** [comment]
![image](https://github.com/user-attachments/assets/fd8ebbf4-6213-4afa-8622-a853c5f573c3)

**Comment by Roger92** [comment]
Alright... version 3.3.0 is released... have a try ;) @NBSamael

**Comment by NBSamael** [comment]
It works just fine!
Thank you very much for your availability and for your work.

**Comment by Roger92** [comment]
No problem... Have fun with the module :) And let me know if there is a module, with which it doesnt work. 

Its implemented more dynamic now. So it shouldnt matter how the label is structured, as long as my module can find it. :)
