### ISSUE TITLE
Suggestion : Allow the GM to set the conversion and a more flexible system for other measurements system 

### ISSUE THREAD

**Issue by rectulo** [Roger92/metric-ruler-labels#7]
Hi Roger !
It's a very cool module for us to use. We will test it during our next session.

I have two suggestion 

1. add an option in the UI for the GM to set conversion
The converter states 1 mile =1,61 km. That's ok.
Alas ! In some of the settings, this is set to 1,5 km. It's a way to easy the life of players ans GM (example : the metric system in Pathfinder 1&2, D&D5 in french and I guess others too). 
It would be cool to allow the user to have a personal conversion.

2. add an option in the UI for the GM to choose another custom measurement system
It would be great to allow displaying other measurements system, ("squares", old french measurements "lieues", "coudées", or the ancient chinese system "chi, bu, li"). 
Allow the user to provide the abbreviation he wants to display ? ft, m, li, co, ca...

Many Thanks !
Rectulo (french member of "La Fonderie")

**Comment by Roger92** [comment]
Hi, yeah let me know if it helped you in your session. :)

Two nice suggestions. I will add them on my list and see ... will need to do some small research on how the settings are handled (so that the GM configures the units etc.)... But yeah sounds like a nice idea.

**Comment by Roger92** [comment]
so you would like to have the original + 2 additional conversions?

**Comment by Roger92** [comment]
Yah, got it :) .... Will take a look on this once i have some free time.

**Comment by Roger92** [comment]
Heyho, later today or maybe tomorrow there will be a version, where you will be able to define your own conversion :) Had some time today to code a little ;)

**Comment by Pubmaster32** [comment]
Sounds awesome! Thank you.

**Comment by Roger92** [comment]
Should be out :) Let me know if that helps you.

**Comment by rectulo** [comment]
Many Thanks !

**Comment by Roger92** [comment]
I will close this issue for now.... if you have any problems with the new version then just open a new one :)
