### ISSUE TITLE
Splendide !

### ISSUE THREAD

**Issue by Vazzimolo** [Roger92/metric-ruler-labels#8]
Super module qui me sauve la vie de MJ.
Le double affichage des mesures est très appréciés de joueurs comme pour le MJ.

Le problèmes c'est qu'il faut que je repasse mes scènes en pieds pour en bénéficier et donc refaire les lumières et les sons mais cela en vaut vraiment le coup.

J'ai remarqué que lorsque la scène est en mètre le module n'affiche pas les pieds ce serait peut être utile que cela fonctionne dans les 2 sens.

Encore merci.

**Comment by Roger92** [comment]
Can you repeat that in english :D

**Comment by Roger92** [comment]
You can now create your own conversion with the new version of the module... That should solve your problem if google translated your issue correctly :)
