### ISSUE TITLE
Suggestion: do the opposite

### ISSUE THREAD

**Issue by Luisphigor** [Roger92/metric-ruler-labels#9]
Hi, 
It would be very convenient if the opposite could also be done: in a world set in meters, add labels in feets. This would be useful for those who use English manuals and play games where the metric system is used.

thanks for you module.

**Comment by Roger92** [comment]
Heyho, thanks for the suggestion... some else suggested something similar. Mabe a userdefined conversion number including a lable like "m" or "ft" would be a way to support this.

So you can tell the module what conversion calculation it shall do and what lable it should put behind that number.

**Comment by Luisphigor** [comment]
Nice, thanks

**Comment by Roger92** [comment]
Heyho, later today or maybe tomorrow there will be a version, where you will be able to define your own conversion :)

**Comment by Luisphigor** [comment]
Great! Thank you!

**Comment by Roger92** [comment]
Its released, feel free to update :)

**Comment by Roger92** [comment]
I will close this issue for now.... if you have any problems with the new version then just open a new one :)
